import turtle
turtle.shape('turtle')
for i in range(3):
    turtle.left(120)
    turtle.forward(50)
turtle.right(30)
turtle.up()
turtle.forward(30)
turtle.pendown()
turtle.left(45)
for i in range(4):
    turtle.left(90)
    turtle.forward(100)
turtle.right(45)
turtle.up()
turtle.forward(30)
turtle.pendown()
turtle.left(54)
for i in range(5):
    turtle.left(72)
    turtle.forward(125)
turtle.right(54)
turtle.up()
turtle.forward(30)
turtle.pendown()
turtle.left(54)
for i in range(6):
    turtle.left(60)
    turtle.forward(150)
turtle.right(60)
turtle.up()
turtle.forward(30)
turtle.pendown()
turtle.left(60)
for i in range(7):
    turtle.left(180- 900/7)
    turtle.forward(175)
turtle.right(180- 900/7)
turtle.up()
turtle.forward(30)
turtle.pendown()
turtle.left(180- 900/7)
for i in range(8):
    turtle.left(180- 135)
    turtle.forward(200)
